# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8dc689df5e38ed084049ef61706f2402"
application_url = "https://calendar-boulder-interested-it.trycloudflare.com"
embedded = true
name = "order-edit-app"
handle = "order-edit-app-3"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "order-edit-test.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_order_edits,write_orders,write_products,customer_read_customers,customer_read_orders, unauthenticated_read_product_listings"

[auth]
redirect_urls = [
  "https://calendar-boulder-interested-it.trycloudflare.com/auth/callback",
  "https://calendar-boulder-interested-it.trycloudflare.com/auth/shopify/callback",
  "https://calendar-boulder-interested-it.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
